/* LÈLE ESSENTIALS — STORE CONFIGURATION
   Prices are set in BDT in the PRODUCTS array below.
   To add a new product, add an object below, supply its image, and create a detail page.
   This static GitHub Pages site uses WhatsApp for customer-submitted COD orders.
*/
const STORE = Object.freeze({name:'Lèle Essentials Co.', whatsapp:'8801729228117', phone2:'8801970155970', currency:'BDT'});
const PRODUCTS = [
 {id:'sakura-set', slug:'sakura-set', name:'Japan Sakura Skincare Ritual Set', label:'THE COMPLETE RITUAL', brand:'LAIKOU', category:'Skincare Sets', size:'5-piece collection', image:'sakura-set.webp', price:1085, badge:'The full ritual', tone:'rose', short:'Five beautifully coordinated essentials for a thoughtful daily skincare routine.', intro:'A considered five-step ritual in delicate sakura-pink packaging. The collection pairs a cleanser, toner, serum, eye cream and essence cream for a complete everyday routine.', includes:[['Cleanser','50 g'],['Toner','100 ml'],['Serum','17 ml'],['Eye cream','15 g'],['Essence cream','25 g']], highlights:['A five-piece routine','Sakura-inspired collection','A beautiful giftable set'], directions:['Cleanse gently and rinse thoroughly.','Apply toner to clean skin.','Smooth on a few drops of serum.','Gently pat eye cream around the orbital area, avoiding direct contact with eyes.','Finish with essence cream. Use daytime sunscreen separately.'], notes:'Retailer listings identify these five items and sizes, and list the country of origin as China; “Japan Sakura” is the product name, not a manufacturing-origin claim. Ingredient references vary by listing; consult your physical packaging for the full ingredient list.'},
 {id:'sakura-mask', slug:'sakura-mask', name:'Japan Sakura Mud Mask', label:'THE SOFT RESET', brand:'LAIKOU', category:'Face Masks', size:'Pack of 12 sachets · 5 g each', image:'sakura-12-pack.webp', price:390, badge:'12 sachets', tone:'rose', short:'A pack of 12 sakura-inspired mud mask sachets for your facial-care routine.', intro:'One purchase includes 12 individually packed Sakura mud mask sachets (5 g per sachet, as labeled). The pink sachet features cherry blossoms and Mount Fuji artwork. Packaging describes hydration, gentle cleansing and oil control. The image illustrates the contents of a 12-sachet pack using the supplied individual sachet photograph.', includes:[['What you receive','12 individual sachets'],['Per sachet','5 g / 0.18 oz (packaging label)'],['Total labeled contents','60 g across 12 sachets'],['Brand','LAIKOU']], highlights:['Hydrating — packaging claim','Gentle cleansing — packaging claim','Oil-control — packaging claim'], directions:['Check the back-of-pack directions before use.','Patch-test first and avoid broken or irritated skin.','Keep away from eyes and lips; rinse immediately if irritation occurs.','Follow the timing and rinsing instructions printed on your sachet.'], notes:'Price is for a 12-sachet pack, not a single sachet. The product image is a composite showing 12 repetitions of the supplied single-sachet photograph. Each sachet is labeled 5 g. The supplied front label does not show the full ingredient list or application time; follow the instructions on your actual packaging.'},
 {id:'matcha-mask', slug:'matcha-mask', name:'Matcha Mud Mask', label:'THE GREEN RESET', brand:'LAIKOU', category:'Face Masks', size:'Pack of 12 sachets · 5 g each', image:'matcha-12-pack.webp', price:390, badge:'12 sachets', tone:'sage', short:'A pack of 12 matcha-inspired mud mask sachets for your facial-care routine.', intro:'One purchase includes 12 individually packed Matcha mud mask sachets (5 g per sachet, as labeled). The sachet is presented in matcha green with powdered-tea artwork. Packaging promotes cleansing and hydration. The image illustrates the contents of a 12-sachet pack using the supplied individual sachet photograph.', includes:[['What you receive','12 individual sachets'],['Per sachet','5 g / 0.18 oz (packaging label)'],['Total labeled contents','60 g across 12 sachets'],['Brand','LAIKOU']], highlights:['Deep cleansing — packaging claim','Hydrating — packaging claim','Acne-related claims appear on the packaging; results are not guaranteed'], directions:['Read the instructions and ingredients on the actual sachet before applying.','Patch-test first; do not use on irritated or broken skin.','Avoid contact with eyes and lips.','Follow the manufacturer’s application time and rinse instructions.'], notes:'Price is for a 12-sachet pack, not a single sachet. The product image is a composite showing 12 repetitions of the supplied single-sachet photograph. Each sachet is labeled 5 g. Packaging makes acne-related claims, but results are not guaranteed and this cosmetic is not represented as medical acne treatment. Verify ingredients and directions on the actual packaging.'},
 {id:'mask-combo', slug:'mask-combo', name:'Sakura + Matcha Mud Mask Duo', label:'THE DOUBLE RITUAL', brand:'LAIKOU', category:'Bundles', size:'2 packs · 24 sachets total (12 + 12) · 5 g each', image:'sakura-matcha-combo.webp', price:720, compareAt:780, badge:'Save ৳60 · 24 sachets', tone:'rose', short:'Two complete 12-sachet packs: Sakura and Matcha together for ৳720, saving ৳60.', intro:'A duo of LAIKOU mud mask packs. Receive one Sakura pack of 12 sachets and one Matcha pack of 12 sachets: 24 individual 5 g sachets in total. The combo saves ৳60 compared with buying both packs separately (৳390 + ৳390 = ৳780). The pack-content illustration repeats the supplied individual sachet photos; it is not a photograph of an outer multipack box.', includes:[['Japan Sakura Mud Mask','12 sachets × 5 g'],['Matcha Mud Mask','12 sachets × 5 g'],['Total','24 sachets · 120 g labeled total'],['Regular combined price','৳780'],['Combo savings','৳60']], highlights:['Two different mask styles in one order','12 Sakura + 12 Matcha sachets','Save ৳60 versus separate packs'], directions:['Check instructions and ingredient lists on both sachet types.','Patch-test each product separately before use.','Use the masks according to their individual manufacturer directions; avoid eyes and irritated skin.'], notes:'You receive two 12-sachet packs (24 sachets total), not 12 mixed sachets. The gallery is a composite made using the provided single-sachet images; physical 12-pack packaging may differ. Delivery is extra and will be confirmed before dispatch.'}
];
const byId = Object.fromEntries(PRODUCTS.map(p=>[p.id,p]));
const asset = p => `${document.body.dataset.root || ''}assets/${p.image}`;
const detail = p => `${document.body.dataset.root || ''}products/${['sakura-set','sakura-mask','matcha-mask','mask-combo'].includes(p.slug) ? p.slug + '.html' : 'item.html?id=' + encodeURIComponent(p.id)}`;
const money = p => Number.isFinite(p.price) ? `৳${p.price.toLocaleString('en-BD')}` : 'Price on request';
const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
let cart = {};
try {const raw=JSON.parse(localStorage.getItem('lele_cart_v3')||'{}'); if(raw && typeof raw==='object') for(const [id,q] of Object.entries(raw)) if(byId[id]&&Number.isSafeInteger(q)&&q>0) cart[id]=Math.min(q,99);} catch {}
function save(){try{localStorage.setItem('lele_cart_v3',JSON.stringify(cart));}catch{} updateCart();}
function add(id,qty=1){if(!byId[id])return;cart[id]=Math.min(99,(cart[id]||0)+qty);save();openCart();announce(`${byId[id].name} added to bag`);}
function updateQty(id,diff){if(!byId[id])return;const n=(cart[id]||0)+diff;if(n<=0)delete cart[id];else cart[id]=Math.min(99,n);save();}
function announce(s){const el=$('#announce');if(el)el.textContent=s;}
function cartItems(){return Object.entries(cart).filter(([id,q])=>byId[id]&&q>0).map(([id,q])=>({...byId[id],qty:q}));}
function updateCart(){const items=cartItems(),total=items.reduce((s,p)=>s+p.qty,0);$$('[data-cart-count]').forEach(e=>e.textContent=total);const list=$('#cart-items');if(!list)return;list.innerHTML=items.length?items.map(p=>`<article class="bag-item"><img src="${asset(p)}" alt="${p.name}" width="96" height="100"><div><a class="bag-item-title" href="${detail(p)}">${p.name}</a><p>${p.size} · ${money(p)}</p><div class="qty-control"><button aria-label="Remove one ${p.name}" data-qty="-1" data-id="${p.id}">−</button><span>${p.qty}</span><button aria-label="Add one ${p.name}" data-qty="1" data-id="${p.id}">+</button></div></div><button class="remove-item" data-remove="${p.id}" aria-label="Remove ${p.name}">×</button></article>`).join(''):'<div class="empty-bag"><span class="empty-symbol">✿</span><h3>Your bag awaits.</h3><p>Thoughtful little luxuries are only a moment away.</p><button class="button button-dark" data-close-cart>Explore the collection</button></div>';
const summary=$('#bag-summary');if(summary){const allPriced=items.length&&items.every(p=>Number.isFinite(p.price));summary.textContent=allPriced?`Subtotal · ৳${items.reduce((s,p)=>s+p.price*p.qty,0).toLocaleString('en-BD')}`:'Delivery is calculated and confirmed on WhatsApp before dispatch.';}
const checkout=$('#checkout-open');if(checkout)checkout.disabled=!items.length;
}
function openCart(){const e=$('#cart-drawer'),b=$('#overlay');if(!e||!b)return;e.classList.add('is-open');e.setAttribute('aria-hidden','false');b.hidden=false;document.body.classList.add('locked');$('#cart-close')?.focus();}
function closeCart(){const e=$('#cart-drawer'),b=$('#overlay');e?.classList.remove('is-open');e?.setAttribute('aria-hidden','true');if(b)b.hidden=true;document.body.classList.remove('locked');}
function openCheckout(){if(!cartItems().length)return;closeCart();const modal=$('#checkout-modal');modal.hidden=false;document.body.classList.add('locked');$('#customer-name')?.focus();const summary=$('#checkout-products');if(summary)summary.innerHTML=cartItems().map(p=>`<div><span>${p.name} × ${p.qty}</span><strong>${Number.isFinite(p.price)?`৳${(p.price*p.qty).toLocaleString('en-BD')}`:money(p)}</strong></div>`).join('');}
function closeCheckout(){const modal=$('#checkout-modal');if(modal)modal.hidden=true;document.body.classList.remove('locked');}
function productCard(p){return `<article class="product-card"><a class="product-card-image ${p.tone}" href="${detail(p)}" aria-label="View ${p.name}"><span class="card-tag">${p.badge}</span><img src="${asset(p)}" alt="Product image of ${p.brand} ${p.name}" loading="lazy" width="700" height="700"><span class="card-view">Discover the ritual ↗</span></a><div class="product-card-info"><div class="eyebrow">${p.brand} · ${p.category}</div><a href="${detail(p)}" class="card-name">${p.name}</a><p>${p.short}</p><div class="product-card-bottom"><span>${p.compareAt?`<del class="was-price">৳${p.compareAt}</del> `:''}${money(p)}</span><button class="round-add" data-add="${p.id}" aria-label="Add ${p.name} to bag">+</button></div></div></article>`;}
function renderHome(){const g=$('#product-grid');if(!g)return;let active='All';const filters=$$('#filters button');const render=()=>{const term=($('#search-products')?.value||'').trim().toLowerCase();const items=PRODUCTS.filter(p=>(active==='All'||p.category===active)&&`${p.name} ${p.category} ${p.short}`.toLowerCase().includes(term));g.innerHTML=items.map(productCard).join('')||'<p class="no-results">No rituals match your search. Try another word.</p>';};filters.forEach(btn=>btn.addEventListener('click',()=>{active=btn.dataset.filter;filters.forEach(x=>{x.classList.toggle('active',x===btn);x.setAttribute('aria-pressed',String(x===btn));});render();}));$('#search-products')?.addEventListener('input',render);render();}
function renderProduct(){const id=document.body.dataset.product || new URLSearchParams(location.search).get('id'),p=byId[id];if(!p){if(document.body.dataset.page==='product'){const h=$('#product-name');if(h)h.textContent='Product not found';const d=$('#product-description');if(d)d.textContent='This product is not available in our current collection. Please return to the shop.';const b=$('#product-add');if(b)b.disabled=true;}return;}document.title=`${p.name} | Lèle Essentials Co.`;$('#product-name').textContent=p.name;$('#product-label').textContent=p.label;$('#product-description').textContent=p.intro;$('#product-size').textContent=p.size;$('#product-price').textContent=money(p);$('#product-main-image').src=asset(p);$('#product-main-image').alt=`Product illustration or photograph of ${p.name} packaging`;
$('#product-includes').innerHTML=p.includes.map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');$('#product-highlights').innerHTML=p.highlights.map(x=>`<li>${x}</li>`).join('');$('#product-directions').innerHTML=p.directions.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><p>${x}</p></li>`).join('');$('#product-notes').textContent=p.notes;$('#product-add').dataset.add=p.id;$('#related-products').innerHTML=PRODUCTS.filter(x=>x.id!==id).map(productCard).join('');const crumbs=$('#breadcrumb-current');if(crumbs)crumbs.textContent=p.name;}
function sendOrder(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const data=new FormData(form),name=String(data.get('name')||'').trim(),phone=String(data.get('phone')||'').replace(/[\s-]/g,''),email=String(data.get('email')||'').trim(),district=String(data.get('district')||'').trim(),division=String(data.get('division')||''),address=String(data.get('address')||'').trim(),notes=String(data.get('notes')||'').trim();
if(!/^(?:\+?880|0)1[3-9]\d{8}$/.test(phone)){alert('Please enter a valid Bangladeshi mobile number (e.g., 017XXXXXXXX).');return;}
const items=cartItems();if(!items.length){alert('Your bag is empty.');return;}
const priced=items.every(p=>Number.isFinite(p.price));const subtotal=priced?`৳${items.reduce((s,p)=>s+p.price*p.qty,0).toLocaleString('en-BD')}`:'To be confirmed by the store';const msg=[`*NEW CASH ON DELIVERY ORDER — ${STORE.name}*`,'',...items.map((p,i)=>`${i+1}. ${p.name} (${p.size}) × ${p.qty} — ${money(p)} each${Number.isFinite(p.price)?` (line total ৳${(p.price*p.qty).toLocaleString('en-BD')})`:``}`),'',`*Product subtotal:* ${subtotal}`,'*Delivery fee:* To be confirmed','*Payment:* Cash on Delivery','','*CUSTOMER DETAILS*',`Name: ${name}`,`Mobile: ${phone}`,...(email?[`Email: ${email}`]:[]),`Division: ${division}`,`District: ${district}`,`Full address: ${address}`,`Notes: ${notes||'None'}`,'','Please confirm availability, final total and delivery details before dispatch.'];
const url=`https://wa.me/${STORE.whatsapp}?text=${encodeURIComponent(msg.join('\n'))}`;const link=$('#whatsapp-fallback');if(link){link.href=url;link.hidden=false;}const win=window.open(url,'_blank');if(win){try{win.opener=null;}catch(e){}}const status=$('#checkout-status');if(status)status.textContent=win?'WhatsApp opened with your order. Please press Send there to submit it.':'Your WhatsApp order message is ready. Select the link below to open WhatsApp and press Send.';
}
function setup(){renderHome();renderProduct();updateCart();document.addEventListener('click',e=>{const t=e.target.closest('button,[data-open-cart],[data-close-cart]');if(!t)return;if(t.matches('[data-add]'))add(t.dataset.add);else if(t.matches('[data-qty]'))updateQty(t.dataset.id,Number(t.dataset.qty));else if(t.matches('[data-remove]')){delete cart[t.dataset.remove];save();}else if(t.matches('[data-open-cart]'))openCart();else if(t.matches('[data-close-cart]'))closeCart();else if(t.matches('#checkout-open'))openCheckout();else if(t.matches('[data-close-checkout]'))closeCheckout();else if(t.matches('[data-menu-toggle]')){const menu=$('#mobile-nav');const show=menu.hidden;menu.hidden=!show;t.setAttribute('aria-expanded',String(show));}});$('#overlay')?.addEventListener('click',closeCart);$('#order-form')?.addEventListener('submit',sendOrder);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeCheckout();}});}
document.addEventListener('DOMContentLoaded',setup);
